[pytest]
pythonpath =
    .
filterwarnings =
    ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*:DeprecationWarning:fastapi\..*
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:fastapi\..*
    ignore:.*doesn't match a supported version!.*
